[package]
name = "xlsx_reader"
version = "1.2.0"
authors = ["OZ <normandiggs@gmail.com>"]
description = "Reader of XLSX files (only data)"
license = "MIT"
repository = "https://github.com/e-oz/xlsx_reader"

[dependencies]
serde_xml = "0.9.1"
zip = "0.2.0"
